AWOS_RECORDS = (
    ('record_type', 5),
    ('id', 4),
    ('sensor_type', 10),
    ('commissioning_status', 1),
    ('commissioning_date', 10),
    ('navaid', 1),
    ('latitude', 14),
    ('longitude', 15),
    ('elevation', 7),
    ('survey_method', 1),
    ('frequency', 7),
    ('second_frequency', 7),
    ('telephone_number', 14),
    ('second_telephone_number', 14),
    ('landing_facility_site_number', 11),
    ('city', 40),
    ('state_post_office_code', 2),
    ('information_effective', 10),
    ('filler', 82),
)
